name: Dictionary Array Check

on:
  pull_request:
    paths:
      - 'src/dictionaries/dictionary.ts'

jobs:
  check-arrays:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check for new arrays
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get the PR diff for dictionary.ts
            const { data: diff } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              mediaType: {
                format: 'diff'
              }
            });

            // Read the current dictionary.ts file
            const dictionaryPath = path.join(process.env.GITHUB_WORKSPACE, 'src/dictionaries/dictionary.ts');
            const content = fs.readFileSync(dictionaryPath, 'utf8');

            // Find new array additions in the diff
            const arrayAdditions = [];
            const diffLines = diff.split('\n');
            let inAddition = false;

            for (const line of diffLines) {
              if (line.startsWith('+') && line.includes('string[]')) {
                const match = line.match(/(\w+):\s*string\[\]/);
                if (match) {
                  arrayAdditions.push(match[1]);
                }
              }
            }

            if (arrayAdditions.length > 0) {
              const comment = [
                '### ⚠️ New Array Types Detected in Dictionary',
                '',
                'I noticed that you\'ve added new array type(s) to the dictionary:',
                arrayAdditions.map(field => `- \`${field}: string[]\``).join('\n'),
                '',
                'Please ensure this follows our array usage guidelines:',
                '- Arrays should only be used for content that naturally varies between languages',
                '- Consider using named keys instead if the content structure is fixed',
                '- Refer to our [Dictionary Arrays Usage Guidelines](src/dictionaries/README.md) for more information',
                '',
                'This is just a friendly reminder - you can proceed if this is intentional.'
              ].join('\n');

              const params = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              };
              await github.rest.issues.createComment(params);
            }
