name: Dictionary Array Check

on:
  pull_request:
    paths:
      - 'src/dictionaries/dictionary.ts'

jobs:
  check-arrays:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check for new arrays
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs').promises;
            const path = require('path');

            try {
              const { data: diff } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                mediaType: {
                  format: 'diff'
                }
              });

              const dictionaryPath = path.join(process.env.GITHUB_WORKSPACE, 'src/dictionaries/dictionary.ts');
              if (!await fs.access(dictionaryPath).then(() => true).catch(() => false)) {
                console.log('dictionary.ts file not found');
                return;
              }

              const content = await fs.readFile(dictionaryPath, 'utf8');

              const arrayAdditions = new Set();
              const diffLines = diff.split('\n');
              
              for (const line of diffLines) {
                if (line.startsWith('+')) {
                  const match = line.match(/^\+\s*([^:\s]+)\s*:\s*(?:readonly\s+)?string\[\s*\]\s*,?\s*$/);
                  if (match) {
                    arrayAdditions.add(match[1]);
                  }
                }
              }

              if (arrayAdditions.size > 0) {
                const comment = [
                  '### ⚠️ New Array Types Detected in Dictionary',
                  '',
                  'I noticed that you\'ve added new array type(s) to the dictionary:',
                  [...arrayAdditions].map(field => `- \`${field}: string[]\``).join('\n'),
                  '',
                  'Please ensure this follows our array usage guidelines:',
                  '- Arrays should only be used for content that naturally varies between languages',
                  '- Consider using named keys instead if the content structure is fixed',
                  '- Refer to our [Dictionary Arrays Usage Guidelines](src/dictionaries/README.md) for more information',
                  '',
                  'This is just a friendly reminder - you can proceed if this is intentional.'
                ].join('\n');

                const params = {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: comment
                };
                await github.rest.issues.createComment(params);
              }
            } catch (error) {
              console.error('Error in array check:', error);
              core.setFailed(`Action failed with error: ${error.message}`);
            }
